version: '3'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: cvcdb
      MYSQL_ROOT_PASSWORD: cvc2021
    ports:
      - "3306:3306"
    volumes:
      - cvc_data://var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8099:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  cvc_data:
