<?php
/**
 * @file
 * Evaluation progress.
 */

 /**
  * Implements hook_theme().
  */
  function esg_progress_theme($existing, $type, $theme, $path)
  {
      return [
          'scoretable' => [
              'variables' => [
                //   'year' => NULL,
                //   'quarter' => NULL,
                'total_count' => NULL,
                'total_score' => NULL,
                'data' => NULL,
                'evaluation_score' => NULL,
              ],
            ],
        ];
  }